### PR TITLE
Add ability to run under AWS Lambda

### PR DESCRIPTION
**Pull request by BryanCrotaz**
Add --region optional cli param to override credentials file (missing on Lambda)
Fall back to EnvironmentVariableCredentialsProvider if credentials file missing
Output API ID to log so that bash can parse it out

### CODE REVIEW

**Comment by s0enke** [comment]
related: #38

**Comment by rpgreen** [comment]
It looks like this is a subset of PR #38. Can you confirm that #38 works for your use-case?

**Comment by BryanCrotaz** [comment]
It is a strict subset - I'll test with #38 and suggest any changes but the code looks good. In Lambda there is no credentials file - it's all in ENV. #38 looks good for that.

**Comment by BryanCrotaz** [comment]
I'll add a new PR for "Output API ID to log so that bash can parse it out"

**Pull request closed without merging**
