### PR TITLE
Added sleep to createMethodParameters

### PR DESCRIPTION
**Pull request by bholbrook73**

### CODE REVIEW

**Comment by sanagrwl** [comment]
Could you elaborate a bit as to why you added sleep to that method? I am curious.

**Comment by bholbrook73** [comment]
The AWS API has a limit of 2 POST's per second. There is a sleep() at the end of each method to ensure that no more than 2 requests get made in that time frame, but each response type per method ALSO fires off an api call. Large sets of response types (in my case individually setting the models for 400,401,500,503 and 200)  would cause too many calls to the AWS API and the importer would error out. Adding the sleep() call during the response creation spaced out the calls enough to stay below the AWS API requests per second limits.

**Comment by sanagrwl** [comment]
Ah, thank you for the clarification.

**Comment by s0enke** [comment]
Not LGTM, usually one uses retry/backoff features of the HTTP client library: http://docs.aws.amazon.com/general/latest/gr/api-retries.html

**Comment by rpgreen** [comment]
@s0enke is correct. There is a known issue with client affecting backoff/retry logic for throttled requests. Use of sleep() is a temporary workaround that we hope to remove soon.

**Pull request closed without merging**
