### PR TITLE
Use default AWS Credentials provider chain

### PR DESCRIPTION
**Pull request by s0enke**
so we do not have to use a hardcoded credentials/config file and we
reuse the default SDK logic to lookup credentials.

BREAKING CHANGE: Also change region lookup to a CLI parameter in order to remove the
dependency to the `.aws/config` which seems to be a feature of the AWS
CLI, but not the Java SDK.

Credentials stored in profiles should still work because the provider
chain includes the `ProfileCredentialsProvider`.

### CODE REVIEW

**Comment by rpgreen** [comment]
This looks good, thanks. Will need to decide on a strategy for merging this since it's a breaking change.

**Comment by jeffdc** [comment]
@rpgreen any more thoughts on this? we are using this to try and automate API Gateway deployments via CloudBees hosted Jenkins and this particular issues is creating some real headaches.

**Comment by s0enke** [comment]
@rpgreen any news here?

**Comment by s0enke** [comment]
rebased against master

**Comment by rpgreen** [comment]
This looks good but I can't merge this change unless it is backwards compatible. Can we update it such that it will look for the SDK region/credentials first, then fallback to the rest of the provider chain? The region parameter should be optional when the SDK credentials are used, but required for the rest of the provider chain.

**Comment by BryanCrotaz** [comment]
Shucks if it's a breaking change - it should be in line with all _other_ uses of the sdk. Just increment the major version and flag the change.

**Comment by rpgreen** [comment]
Hi all,

I just integrated @s0enke's changes and made them backwards compatible. Let me know if any issues

**Comment by BryanCrotaz** [comment]
That means they're not compatible with any other use of the sdk - that's going to lead to all sorts of unexpected behaivour by future users

**Comment by rpgreen** [comment]
What are you proposing? Currently the behavior is exactly the same as the AWS CLI/SDK, which is what we want.

**Pull request closed without merging**
