### PR TITLE
Initial support for RAML import

### PR DESCRIPTION
**Pull request by blakeembrey**
There's a small amount of duplication in the test suites and the common class could (maybe) be refactored further to handle more between both Swagger and RAML, but it all works. The RAML implementation requires you use an external configuration in JSON (currently in the format of `absoluteUri -> method (lowercase) -> auth/integration`) as there's no concept of metadata, but this could be reused for Swagger in the future, where the consumer doesn't want to or can't mutate their Swagger definition (maybe it's public facing).

Edit: Oh, there's the naming thing also - I made some changes around the name/usage instructions to include RAML, but fundamentally the repo will probably need renaming :smile:

### CODE REVIEW

**Comment by rpgreen** [comment]
Looks good in general - thanks! 

I don't foresee the config file being used for the Swagger implementations. Can we make this specific to RAML and name the argument as such? I'm not sure if it belongs in the ApiFileImporter interface.

**Comment by blakeembrey** [comment]
@rpgreen Just pushed up the changes you mentioned. There's probably a nicer way to do the import API in `main`, so I'm open to suggestions there.

**Comment by rpgreen** [comment]
Thanks for the update. Will do a final review next week

**Comment by rpgreen** [comment]
@blakeembrey - finally merged!. Thanks for the help - I hope you continue to contribute!

**Comment by blakeembrey** [comment]
Awesome, cheers! I'll try to keep up with issues :smile:

**Pull request merged**
